export const mock_data = [
  {
    id: 173,
    name: 'الملحق الأدبي',
    description: 'شرح الملحق الأدبي لمادة اللغة الفرنسية',
    cover: 'https://api.tarkeys.net/storage/courses/1768140996___________.png',
    teacher: {
      id: 7,
      name: 'عبد الوهاب كلّاوي',
      about: null,
      image: null,
    },
    subject: {
      id: 26,
      name: 'منهاج الأدبي',
      icon: null,
    },
    academic_year: {
      id: 3,
      name: '2025-2026',
    },
    classroom: {
      id: 1,
      name: 'بكالوريا',
    },
    branch: {
      id: 2,
      name: 'الفرع الأدبي',
    },
    course_type: {
      id: 2,
      name: 'المنهاج',
    },
    price: 50000,
    original_price: 50000,
    is_free: true,
    is_open: true,
    guest_mode: true,
  },
  {
    id: 172,
    name: 'منهاج التربية الإسلامية للأدبي',
    description: 'شرح منهاج التربية الإسلامية للبكالوريا',
    cover: 'https://api.tarkeys.net/storage/courses/1768141195___________.png',
    teacher: {
      id: 10,
      name: 'محمد خير السعدي',
      about: null,
      image:
        'https://api.tarkeys.net/storage/teachers/1768140258_________-______-____________---__________.png',
    },
    subject: {
      id: 26,
      name: 'منهاج الأدبي',
      icon: null,
    },
    academic_year: {
      id: 3,
      name: '2025-2026',
    },
    classroom: null,
    branch: {
      id: 2,
      name: 'الفرع الأدبي',
    },
    course_type: {
      id: 2,
      name: 'المنهاج',
    },
    price: 100000,
    original_price: 100000,
    is_free: false,
    is_open: true,
    guest_mode: true,
  },
  {
    id: 171,
    name: 'منهاج الجغرافيا',
    description: 'شرح منهاج الجغرافيا بشكل كامل',
    cover: 'https://api.tarkeys.net/storage/courses/1768136940_______________.png',
    teacher: {
      id: 6,
      name: 'ضياء الدين عريبي',
      about: null,
      image: null,
    },
    subject: {
      id: 26,
      name: 'منهاج الأدبي',
      icon: null,
    },
    academic_year: {
      id: 3,
      name: '2025-2026',
    },
    classroom: null,
    branch: {
      id: 2,
      name: 'الفرع الأدبي',
    },
    course_type: {
      id: 2,
      name: 'المنهاج',
    },
    price: 225000,
    original_price: 225000,
    is_free: false,
    is_open: true,
    guest_mode: true,
  },
  {
    id: 170,
    name: 'منهاج التاريخ',
    description: 'شرح منهاج التاريخ بشكل كامل',
    cover: 'https://api.tarkeys.net/storage/courses/1768137086___________-2.png',
    teacher: {
      id: 6,
      name: 'ضياء الدين عريبي',
      about: null,
      image: null,
    },
    subject: {
      id: 26,
      name: 'منهاج الأدبي',
      icon: null,
    },
    academic_year: {
      id: 3,
      name: '2025-2026',
    },
    classroom: null,
    branch: {
      id: 2,
      name: 'الفرع الأدبي',
    },
    course_type: {
      id: 2,
      name: 'المنهاج',
    },
    price: 225000,
    original_price: 225000,
    is_free: false,
    is_open: true,
    guest_mode: true,
  },
  {
    id: 168,
    name: 'منهاج العربي للأدبي',
    description: 'شرح منهاج العربي بشكل كامل',
    cover: 'https://api.tarkeys.net/storage/courses/1768136975_________.png',
    teacher: {
      id: 15,
      name: 'خالد عرابي',
      about: null,
      image: null,
    },
    subject: {
      id: 26,
      name: 'منهاج الأدبي',
      icon: null,
    },
    academic_year: {
      id: 3,
      name: '2025-2026',
    },
    classroom: null,
    branch: {
      id: 2,
      name: 'الفرع الأدبي',
    },
    course_type: {
      id: 2,
      name: 'المنهاج',
    },
    price: 300000,
    original_price: 300000,
    is_free: false,
    is_open: true,
    guest_mode: true,
  },
]
